// ─────────────────────────────────────────────────────────────────────────
// System Design Academy — index data
// 150 entries. Field order: [title, url, category, letter]
// Featured deep dives are marked by matching DEEP_DIVE_MAP below.
// ─────────────────────────────────────────────────────────────────────────

const DATA = [
  // CASE STUDIES
  ["Real-Time Gaming Leaderboard","https://systemdesign.one/leaderboard-system-design/","case","#"],
  ["Real-Time Live Comments","https://systemdesign.one/live-comment-system-design/","case","#"],
  ["Distributed Counter","https://systemdesign.one/distributed-counter-system-design/","case","#"],
  ["Real Time Presence Platform","https://systemdesign.one/real-time-presence-platform-system-design/","case","#"],
  ["How to Scale an App to 10 Million Users on AWS","https://newsletter.systemdesign.one/p/aws-scale","case","A"],
  ["How Airbnb Adopted HTTP Streaming to Save 84M USD","https://newsletter.systemdesign.one/p/what-is-critical-rendering-path","case","A"],
  ["Amazon Prime Video Microservices Top Failure","https://newsletter.systemdesign.one/p/prime-video-microservices","case","A"],
  ["How Amazon S3 Achieves 99.999999999% Durability","https://newsletter.systemdesign.one/p/amazon-s3-durability","case","A"],
  ["How Amazon Lambda Works","https://newsletter.systemdesign.one/p/how-does-aws-lambda-work","case","A"],
  ["How Amazon S3 Works","https://newsletter.systemdesign.one/p/s3-architecture","case","A"],
  ["How Do Apple AirTags Work","https://newsletter.systemdesign.one/p/how-do-airtags-work","case","A"],
  ["How Apple Pay Handles 41M Transactions a Day Securely","https://newsletter.systemdesign.one/p/how-does-apple-pay-work","case","A"],
  ["How Amazon S3 Achieves Strong Consistency","https://newsletter.systemdesign.one/p/s3-strong-consistency","case","A"],
  ["Bitly URL Shortener Architecture","https://systemdesign.one/url-shortening-system-design/","case","B"],
  ["How Does Bluesky Work","https://newsletter.systemdesign.one/p/how-does-bluesky-work","case","B"],
  ["How Canva Supports Real-Time Collaboration for 135M Users","https://newsletter.systemdesign.one/p/rsocket","case","C"],
  ["How Cloudflare Supports 55M RPS With Only 15 Postgres Clusters","https://newsletter.systemdesign.one/p/postgresql-scalability","case","C"],
  ["How Disney+ Hotstar Delivered 5 Billion Emojis in Real Time","https://newsletter.systemdesign.one/p/hotstar-architecture","case","D"],
  ["How Disney+ Hotstar Scaled to 25M Concurrent Users","https://newsletter.systemdesign.one/p/hotstar-scaling","case","D"],
  ["How Disney+ Scaled to 11M Users on Launch Day","https://newsletter.systemdesign.one/p/disney-architecture","case","D"],
  ["How Discord Boosts Performance With Code-Splitting","https://newsletter.systemdesign.one/p/what-is-code-splitting-in-react","case","D"],
  ["How Dropbox Scaled to 100K Users in a Year After Launch","https://newsletter.systemdesign.one/p/dropbox-architecture","case","D"],
  ["How Facebook Scaled Live Video to a Billion Users","https://newsletter.systemdesign.one/p/live-streaming-architecture","case","F"],
  ["How Facebook Supports a Billion Users via Software Load Balancer","https://newsletter.systemdesign.one/p/facebook-load-balancer","case","F"],
  ["How Figma Scaled Postgres to 4M Users","https://newsletter.systemdesign.one/p/postgres-scale","case","F"],
  ["How Google Search Works","https://newsletter.systemdesign.one/p/search-engine-architecture","case","G"],
  ["How Giphy Delivers 10B GIFs a Day to 1B Users","https://newsletter.systemdesign.one/p/cdn-explained","case","G"],
  ["How to Scale an App to 100M Users on GCP","https://newsletter.systemdesign.one/p/google-cloud-scalability","case","G"],
  ["How Google Docs Works","http://newsletter.systemdesign.one/p/how-does-google-docs-work","case","G"],
  ["How Hashnode Generates Feed at Scale","https://newsletter.systemdesign.one/p/feed-architecture","case","H"],
  ["How Halo Scaled to 11.6M Users Using the Saga Design Pattern","https://newsletter.systemdesign.one/p/saga-design-pattern","case","H"],
  ["How Instagram Scaled to 2.5 Billion Users","https://newsletter.systemdesign.one/p/instagram-infrastructure","case","I"],
  ["How Khan Academy Scaled to 30 Million Users","https://newsletter.systemdesign.one/p/khan-academy-architecture","case","K"],
  ["How LinkedIn Scaled to 930 Million Users","https://newsletter.systemdesign.one/p/scalable-software-architecture","case","L"],
  ["How LinkedIn Adopted Protocol Buffers to Reduce Latency by 60%","https://newsletter.systemdesign.one/p/protocol-buffers-vs-json","case","L"],
  ["Tech Stack Evolution at Levels.fyi","https://newsletter.systemdesign.one/p/levels-fyi-google-sheets","case","L"],
  ["How Lyft Supports Rides to 21 Million Users","https://newsletter.systemdesign.one/p/lyft-engineering","case","L"],
  ["How McDonald's Food Delivery Handles 20,000 Orders/Second","https://newsletter.systemdesign.one/p/mcdonalds-architecture","case","M"],
  ["How Meta Achieves 99.99999999% Cache Consistency","https://newsletter.systemdesign.one/p/cache-consistency","case","M"],
  ["How Does Netflix Work?","https://newsletter.systemdesign.one/p/how-does-netflix-work","case","N"],
  ["Microservices Lessons From Netflix","https://newsletter.systemdesign.one/p/netflix-microservices","case","N"],
  ["How Netflix Uses Chaos Engineering to Create Resilient Systems","https://newsletter.systemdesign.one/p/chaos-engineering","case","N"],
  ["How PayPal Supports a Billion Transactions/Day With Only 8 VMs","https://newsletter.systemdesign.one/p/actor-model","case","P"],
  ["Pastebin","https://systemdesign.one/system-design-pastebin/","case","P"],
  ["How Quora Shards MySQL to Handle 13+ Terabytes","https://newsletter.systemdesign.one/p/mysql-sharding","case","Q"],
  ["How Razorpay Scaled to Handle Flash Sales at 1500 RPS","https://newsletter.systemdesign.one/p/payment-gateway-architecture","case","R"],
  ["How Reddit Works","https://newsletter.systemdesign.one/p/reddit-architecture","case","R"],
  ["Slack Architecture","https://systemdesign.one/slack-architecture/","case","S"],
  ["Virtual Waiting Room Architecture at SeatGeek","https://newsletter.systemdesign.one/p/virtual-waiting-room","case","S"],
  ["How Shopify Handles Flash Sales at 32M Requests/Minute","https://newsletter.systemdesign.one/p/shopify-flash-sale","case","S"],
  ["How Stripe Does Rate Limiting to Build Scalable APIs","https://newsletter.systemdesign.one/p/rate-limiter","case","S"],
  ["How Stripe Prevents Double Payment Using Idempotent API","https://newsletter.systemdesign.one/p/idempotent-api","case","S"],
  ["Tumblr Database Migration Strategy With 60+ Billion Rows","https://newsletter.systemdesign.one/p/how-to-migrate-a-mysql-database","case","T"],
  ["6 Proven Guidelines on Open Sourcing From Tumblr","https://newsletter.systemdesign.one/p/open-source-guidelines","case","T"],
  ["How Tinder Scaled to 1.6 Billion Swipes per Day","https://newsletter.systemdesign.one/p/tinder-architecture","case","T"],
  ["How Uber Computes ETA at Half a Million RPS","https://newsletter.systemdesign.one/p/uber-eta","case","U"],
  ["How Uber Finds Nearby Drivers at 1 Million RPS","https://newsletter.systemdesign.one/p/how-does-uber-find-nearby-drivers","case","U"],
  ["How Uber Payment System Handles 30M Transactions Per Day","https://newsletter.systemdesign.one/p/payment-system-design","case","U"],
  ["Why WhatsApp Supports 50B Messages/Day With 32 Engineers","https://newsletter.systemdesign.one/p/whatsapp-engineering","case","W"],
  ["Wechat Architecture That Powers 1.67B Monthly Users","https://newsletter.systemdesign.one/p/chat-application-architecture","case","W"],
  ["Why YouTube Supports 100M Video Views/Day With 9 Engineers","https://newsletter.systemdesign.one/p/youtube-scalability","case","Y"],
  ["How YouTube Supports 2.49B Users With MySQL","https://newsletter.systemdesign.one/p/vitess-mysql","case","Y"],
  ["Why Zoom Supports 300M Video Calls/Day","https://newsletter.systemdesign.one/p/zoom-architecture","case","Z"],
  ["How Zapier Automates Billions of Tasks","https://newsletter.systemdesign.one/p/zapier-architecture","case","Z"],

  // FUNDAMENTALS
  ["Back of the Envelope","https://systemdesign.one/back-of-the-envelope/","fund","#"],
  ["How to Troubleshoot if You Can't Access a Website","https://systemdesign.one/how-to-troubleshoot-if-you-cannot-access-a-website/","fund","#"],
  ["What Happens When You Type a URL Into Your Browser?","https://systemdesign.one/what-happens-when-you-type-url-into-your-browser/","fund","#"],
  ["System Design Interview Cheat Sheet","https://systemdesign.one/system-design-interview-cheatsheet/","fund","#"],
  ["Software Engineer Interview Learning Resources","https://systemdesign.one/software-engineer-interview-learning-resources/","fund","#"],
  ["7 Simple Ways to Fail System Design Interview","https://newsletter.systemdesign.one/p/design-system-newsletter","fund","#"],
  ["Amazon Frugal Architecture Explained","https://newsletter.systemdesign.one/p/frugal-architecture","fund","#"],
  ["11 System Design Concepts Explained, Simply","https://newsletter.systemdesign.one/p/11-system-design-concepts-explained","fund","#"],
  ["114 System Design Concepts — Part 1","https://newsletter.systemdesign.one/p/system-design-concepts","fund","#"],
  ["114 System Design Concepts — Part 2","https://newsletter.systemdesign.one/p/system-design-core-concepts","fund","#"],
  ["114 System Design Concepts — Part 3","https://newsletter.systemdesign.one/p/system-design-fundamentals","fund","#"],
  ["How Timsort Algorithm Works","https://newsletter.systemdesign.one/p/timsort-algorithm","fund","#"],
  ["Mobile System Design Concepts — Part 1","https://newsletter.systemdesign.one/p/mobile-system-design","fund","#"],
  ["Actor Model","https://newsletter.systemdesign.one/p/actor-model","fund","A"],
  ["How API Gateway Works","https://newsletter.systemdesign.one/p/how-api-gateway-works","fund","A"],
  ["API Gateway vs Load Balancer vs Reverse Proxy","https://newsletter.systemdesign.one/p/api-gateway-load-balancer-reverse-proxy","fund","A"],
  ["Best Practices for API Design","https://newsletter.systemdesign.one/p/best-practices-for-api-design","fund","A"],
  ["Best Practices for API Security","https://newsletter.systemdesign.one/p/api-security-best-practices","fund","A"],
  ["API Versioning","https://newsletter.systemdesign.one/p/api-versioning","fund","A"],
  ["Bloom Filter","https://systemdesign.one/bloom-filters-explained/","fund","B"],
  ["Cell Based Architecture","https://newsletter.systemdesign.one/p/cell-based-architecture","fund","C"],
  ["Consistency Patterns","https://systemdesign.one/consistency-patterns/","fund","C"],
  ["Top 5 Caching Patterns","https://newsletter.systemdesign.one/p/caching-patterns","fund","C"],
  ["How to Scale Code Reviews","https://newsletter.systemdesign.one/p/how-to-do-code-review","fund","C"],
  ["Code Review Best Practices","https://newsletter.systemdesign.one/p/code-review-best-practices","fund","C"],
  ["Consistent Hashing","https://systemdesign.one/consistent-hashing-explained/","fund","C"],
  ["Concurrency Is Not Parallelism","https://newsletter.systemdesign.one/p/concurrency-is-not-parallelism","fund","C"],
  ["15 Pitfalls That Break Cloud Systems","https://newsletter.systemdesign.one/p/cloud-system-design","fund","C"],
  ["Cybersecurity Terms Every Software Engineer Must Know","https://newsletter.systemdesign.one/p/cybersecurity-fundamentals","fund","C"],
  ["The Entire Computer Science Stack, Explained In 51 Images","https://newsletter.systemdesign.one/p/computer-science-101","fund","C"],
  ["How Databases Keep Passwords Securely","https://newsletter.systemdesign.one/p/how-to-store-passwords-in-database","fund","D"],
  ["How DNS Works","https://newsletter.systemdesign.one/p/what-is-a-dns-server-and-how-does-it-work","fund","D"],
  ["Deployment Patterns","https://newsletter.systemdesign.one/p/deployment-patterns","fund","D"],
  ["Distributed Systems Deep Dive","https://newsletter.systemdesign.one/p/distributed-systems","fund","D"],
  ["21 Frontend System Design Concepts","https://newsletter.systemdesign.one/p/frontend-system-design","fund","F"],
  ["Gossip Protocol","https://systemdesign.one/gossip-protocol/","fund","G"],
  ["21 Git Commands","https://newsletter.systemdesign.one/p/commands-in-git","fund","G"],
  ["Hinted Handoff","https://systemdesign.one/hinted-handoff/","fund","H"],
  ["How Does HTTPS Work","https://newsletter.systemdesign.one/p/how-does-https-work","fund","H"],
  ["Must Know HTTP Headers","https://newsletter.systemdesign.one/p/http-headers","fund","H"],
  ["What Is High Availability","https://newsletter.systemdesign.one/p/what-is-high-availability","fund","H"],
  ["How JWT Works","https://newsletter.systemdesign.one/p/how-jwt-works","fund","J"],
  ["How Kafka Works","https://newsletter.systemdesign.one/p/how-kafka-works","fund","K"],
  ["How Load Balancing Algorithms Work","https://newsletter.systemdesign.one/p/load-balancing-algorithms","fund","L"],
  ["Micro Frontends","https://newsletter.systemdesign.one/p/micro-frontends","fund","M"],
  ["How Shopify Handled 30TB/Min With Modular Monolith","https://newsletter.systemdesign.one/p/modular-monolith","fund","M"],
  ["1 Simple Technique to Scale Microservices Architecture","https://newsletter.systemdesign.one/p/how-to-scale-microservices","fund","M"],
  ["How Message Queues Work","https://newsletter.systemdesign.one/p/what-is-a-message-queue","fund","M"],
  ["How Nginx Supports 1M Concurrent Connections on One Server","https://newsletter.systemdesign.one/p/how-does-nginx-work","fund","N"],
  ["Forward Proxy vs Reverse Proxy","https://newsletter.systemdesign.one/p/forward-proxy-vs-reverse-proxy","fund","P"],
  ["Quotient Filter","https://systemdesign.one/quotient-filter-explained/","fund","Q"],
  ["Redis Use Cases","https://newsletter.systemdesign.one/p/redis-use-cases","fund","R"],
  ["Rate Limiting Strategies Explained","https://newsletter.systemdesign.one/p/rate-limiting","fund","R"],
  ["How Remote Procedure Call Works","https://newsletter.systemdesign.one/p/how-rpc-works","fund","R"],
  ["Service Discovery","https://systemdesign.one/what-is-service-discovery/","fund","S"],
  ["How Sidecar Pattern Works","https://newsletter.systemdesign.one/p/sidecar-pattern","fund","S"],
  ["Stacked Diffs, Simply Explained","https://newsletter.systemdesign.one/p/stacked-diffs","fund","S"],
  ["How Stock Exchange Works — Part 1","https://newsletter.systemdesign.one/p/stock-exchange-system-design","fund","S"],
  ["How Stock Exchange Handles Concurrency at Scale — Part 2","https://newsletter.systemdesign.one/p/disruptor-pattern","fund","S"],
  ["Design Stock Exchange: A Deep Dive — Part 3","https://newsletter.systemdesign.one/p/system-design-stock-exchange","fund","S"],
  ["How Do Websockets Work","https://newsletter.systemdesign.one/p/how-do-websockets-work","fund","W"],
  ["How Do Webhooks Work","https://newsletter.systemdesign.one/p/how-do-webhooks-work","fund","W"],

  // INTERVIEW
  ["System Design Interview Framework","https://newsletter.systemdesign.one/p/how-to-prepare-for-system-design-interview","int","#"],
  ["Behavioral Interview Playbook","https://newsletter.systemdesign.one/p/common-behavioral-interview-questions","int","#"],
  ["Mobile System Design Interview Framework","https://newsletter.systemdesign.one/p/mobile-system-design-interview","int","#"],
  ["System Design Interview: Design Airbnb","https://newsletter.systemdesign.one/p/airbnb-system-design","int","A"],
  ["System Design Interview: Design ChatGPT","https://newsletter.systemdesign.one/p/chatgpt-system-design","int","C"],
  ["System Design Interview: Design Spotify","https://newsletter.systemdesign.one/p/spotify-system-design","int","S"],
  ["System Design Interview: Web Crawler & Search Engine","https://newsletter.systemdesign.one/p/web-crawler-system-design","int","S"],
  ["Design Twitter/X Timeline — Frontend Deep Dive","https://newsletter.systemdesign.one/p/system-design-interview-twitter","int","T"],
  ["Design WhatsApp","https://newsletter.systemdesign.one/p/whatsapp-system-design","int","W"],
  ["Design a Chat System (WhatsApp Part 2)","https://newsletter.systemdesign.one/p/design-a-chat-system","int","W"],
  ["Design YouTube","https://newsletter.systemdesign.one/p/youtube-system-design","int","Y"],

  // AI
  ["How AI Agents Work","https://newsletter.systemdesign.one/p/ai-agents-explained","ai","A"],
  ["How to Design Your Own AI Agent","https://newsletter.systemdesign.one/p/how-do-ai-agents-work","ai","A"],
  ["AI Coding Workflow","https://newsletter.systemdesign.one/p/ai-coding-workflow","ai","C"],
  ["What is Context Engineering?","https://newsletter.systemdesign.one/p/what-is-context-engineering","ai","C"],
  ["Context Engineering vs Prompt Engineering","https://newsletter.systemdesign.one/p/context-engineering-vs-prompt-engineering","ai","C"],
  ["How ChatGPT Apps Work","https://newsletter.systemdesign.one/p/apps-in-chatgpt","ai","C"],
  ["LLM Concepts, Simply Explained","https://newsletter.systemdesign.one/p/llm-concepts","ai","L"],
  ["MCP — A Deep Dive","https://newsletter.systemdesign.one/p/how-mcp-works","ai","M"],
  ["What Is Reinforcement Learning","https://newsletter.systemdesign.one/p/what-is-reinforcement-learning","ai","R"],
  ["How RAG Works","https://newsletter.systemdesign.one/p/how-rag-works","ai","R"],

  // WHITE PAPERS
  ["Amazon Dynamo","https://newsletter.systemdesign.one/p/amazon-dynamo-architecture","paper","D"],
  ["Google Spanner","https://newsletter.systemdesign.one/p/cloud-spanner-database","paper","S"],
  ["Meta Serverless Architecture: XFaaS","https://newsletter.systemdesign.one/p/serverless-architecture","paper","X"],
];

// Map article titles (substring match, case-insensitive) → deep-dive page.
// When a card matches, its href is rewritten to the deep-dive and a badge appears.
const DEEP_DIVE_MAP = [
  { match: "rate limit",        href: "topics/rate-limiting.html"      },
  { match: "stripe does rate",  href: "topics/rate-limiting.html"      },
  { match: "caching pattern",   href: "topics/caching-patterns.html"   },
  { match: "message queue",     href: "topics/message-queues.html"     },
  { match: "how kafka works",   href: "topics/message-queues.html"     },
  { match: "consistency pattern", href: "topics/consistency-patterns.html" },
  { match: "api gateway works", href: "topics/api-gateway.html"        },
  { match: "api gateway vs",    href: "topics/api-gateway.html"        },
  { match: "consistent hashing",href: "topics/consistent-hashing.html" },
  { match: "shard",             href: "topics/database-sharding.html"  },
  { match: "figma scaled postgres", href: "topics/database-sharding.html" },
  { match: "quora shards mysql",href: "topics/database-sharding.html"  },
  { match: "vitess",            href: "topics/database-sharding.html"  },
  { match: "idempot",           href: "topics/idempotency-keys.html"   },
  { match: "stripe prevents double", href: "topics/idempotency-keys.html" },
  { match: "saga",              href: "topics/saga-pattern.html"       },
  { match: "halo scaled",       href: "topics/saga-pattern.html"       },
  { match: "distributed transaction", href: "topics/saga-pattern.html" },
  { match: "websocket",         href: "topics/realtime-channels.html"  },
  { match: "real-time presence",href: "topics/realtime-channels.html"  },
  { match: "real-time live comments", href: "topics/realtime-channels.html" },
  { match: "rsocket",           href: "topics/realtime-channels.html"  },
  { match: "circuit breaker",   href: "topics/resilience-polly.html"   },
  { match: "chaos engineering", href: "topics/resilience-polly.html"   },
  { match: "high availability", href: "topics/resilience-polly.html"   },
  { match: "resilience",        href: "topics/resilience-polly.html"   },
  { match: "microservices",     href: "topics/monolith-vs-microservices.html" },
  { match: "monolith",          href: "topics/monolith-vs-microservices.html" },
  { match: "prime video microservices", href: "topics/monolith-vs-microservices.html" },
  { match: "netflix microservices", href: "topics/monolith-vs-microservices.html" },
  { match: "event sourc",       href: "topics/event-sourcing-cqrs.html" },
  { match: "cqrs",              href: "topics/event-sourcing-cqrs.html" },
  { match: "bloom",             href: "topics/bloom-filters.html"      },
  { match: "service discovery", href: "topics/service-discovery.html"  },
  { match: "leader election",   href: "topics/leader-election.html"    },
  { match: "raft",              href: "topics/leader-election.html"    },
  { match: "paxos",             href: "topics/leader-election.html"    },
  { match: "outbox",            href: "topics/change-data-capture.html" },
  { match: "change data capture", href: "topics/change-data-capture.html" },
  { match: "debezium",          href: "topics/change-data-capture.html" },
  { match: "search engine",     href: "topics/search-architecture.html" },
  { match: "elasticsearch",     href: "topics/search-architecture.html" },
  { match: "web crawler",       href: "topics/search-architecture.html" },
  { match: "multi-region",      href: "topics/geographic-distribution.html" },
  { match: "spanner",           href: "topics/geographic-distribution.html" },
  { match: "geographic",        href: "topics/geographic-distribution.html" },
  { match: "global",            href: "topics/geographic-distribution.html" },
  { match: "cdn",               href: "topics/cdn-architecture.html"   },
  { match: "giphy delivers",    href: "topics/cdn-architecture.html"   },
  { match: "http streaming",    href: "topics/cdn-architecture.html"   },
  { match: "jwt",               href: "topics/jwt-vs-sessions.html"    },
  { match: "session",           href: "topics/jwt-vs-sessions.html"    },
  { match: "password",          href: "topics/jwt-vs-sessions.html"    },
  { match: "https",             href: "topics/jwt-vs-sessions.html"    },
  { match: "grpc",              href: "topics/grpc-rest-graphql.html"  },
  { match: "graphql",           href: "topics/grpc-rest-graphql.html"  },
  { match: "protocol buffer",   href: "topics/grpc-rest-graphql.html"  },
  { match: "rpc",               href: "topics/grpc-rest-graphql.html"  },

  // CASE STUDIES
  { match: "discord",           href: "topics/case-discord-cassandra.html" },
  { match: "figma scaled postgres to 4m", href: "topics/case-figma-postgres.html" },
  { match: "stripe does rate", href: "topics/case-stripe-rate-limiting.html" },
  { match: "stripe prevents double", href: "topics/case-stripe-rate-limiting.html" },
  { match: "chaos engineering", href: "topics/case-netflix-chaos.html"  },
  { match: "cloudflare supports 55m", href: "topics/case-cloudflare-postgres.html" },
  { match: "hotstar",           href: "topics/case-hotstar-concurrent.html" },
  { match: "actor model",       href: "topics/case-paypal-actor.html"  },
  { match: "paypal",            href: "topics/case-paypal-actor.html"  },
  { match: "shopify handles flash", href: "topics/case-shopify-flash.html" },

  // FUNDAMENTALS
  { match: "https",             href: "topics/fundamental-https.html"  },
  { match: "dns",               href: "topics/fundamental-dns.html"    },
  { match: "kafka",             href: "topics/fundamental-kafka.html"  },
  { match: "deployment pattern",href: "topics/fundamental-deployment.html" },
  { match: "load balancing",    href: "topics/fundamental-load-balancing.html" },
  { match: "sidecar",           href: "topics/fundamental-sidecar.html" },
  { match: "webhook",           href: "topics/fundamental-webhooks.html" },
  { match: "cell based",        href: "topics/fundamental-cell-architecture.html" },

  // INTERVIEWS
  { match: "interview framework", href: "topics/interview-framework.html" },
  { match: "how to prepare for system design", href: "topics/interview-framework.html" },
  { match: "design whatsapp",   href: "topics/interview-design-whatsapp.html" },
  { match: "design a chat",     href: "topics/interview-design-whatsapp.html" },
  { match: "design youtube",    href: "topics/interview-design-youtube.html" },
  { match: "design spotify",    href: "topics/interview-design-spotify.html" },
  { match: "design chatgpt",    href: "topics/interview-design-chatgpt.html" },
  { match: "web crawler",       href: "topics/interview-design-web-crawler.html" },

  // AI
  { match: "rag works",         href: "topics/ai-rag.html"             },
  { match: "ai agent",          href: "topics/ai-agents.html"          },
  { match: "design your own ai", href: "topics/ai-agents.html"         },
  { match: "mcp",               href: "topics/ai-mcp.html"             },
  { match: "llm concept",       href: "topics/ai-llm-concepts.html"    },

  // WHITE PAPERS
  { match: "amazon dynamo",     href: "topics/paper-dynamo.html"       },
  { match: "google spanner",    href: "topics/paper-spanner.html"      },
  { match: "xfaas",             href: "topics/paper-xfaas.html"        },
  { match: "meta serverless",   href: "topics/paper-xfaas.html"        },

  // AI gaps
  { match: "ai coding workflow", href: "topics/ai-coding-workflow.html"},
  { match: "context engineering", href: "topics/ai-context-engineering.html" },
  { match: "reinforcement learning", href: "topics/ai-reinforcement-learning.html" },
  { match: "chatgpt apps",      href: "topics/ai-chatgpt-apps.html"    },
  { match: "apps in chatgpt",   href: "topics/ai-chatgpt-apps.html"    },

  // INTERVIEW gaps
  { match: "behavioral interview", href: "topics/interview-behavioral.html" },
  { match: "mobile system design interview", href: "topics/interview-mobile-framework.html" },
  { match: "design airbnb",     href: "topics/interview-design-airbnb.html" },
  { match: "twitter/x timeline", href: "topics/interview-design-twitter-frontend.html" },
  { match: "design twitter",    href: "topics/interview-design-twitter-frontend.html" },

  // FUNDAMENTALS gaps
  { match: "back of the envelope", href: "topics/fundamental-back-of-envelope.html" },
  { match: "type a url",        href: "topics/fundamental-url-walkthrough.html" },
  { match: "type url",          href: "topics/fundamental-url-walkthrough.html" },
  { match: "best practices for api design", href: "topics/fundamental-api-design.html" },
  { match: "api security",      href: "topics/fundamental-api-design.html" },
  { match: "api versioning",    href: "topics/fundamental-api-versioning.html" },
  { match: "high availability", href: "topics/fundamental-high-availability.html" },
  { match: "gossip",            href: "topics/fundamental-gossip.html" },
  { match: "nginx",             href: "topics/fundamental-nginx.html" },
  { match: "frontend system design", href: "topics/fundamental-frontend-system-design.html" },
  { match: "stock exchange",    href: "topics/fundamental-stock-exchange.html" },
  { match: "disruptor",         href: "topics/fundamental-stock-exchange.html" },
  { match: "distributed systems", href: "topics/fundamental-distributed-systems.html" },

  // CASE STUDIES gaps
  { match: "uber finds nearby", href: "topics/case-uber-nearby.html"   },
  { match: "uber computes",     href: "topics/case-uber-nearby.html"   },
  { match: "instagram scaled",  href: "topics/case-instagram-scale.html" },
  { match: "instagram scaled to 2.5", href: "topics/case-instagram-scale.html" },
  { match: "slack architecture", href: "topics/case-slack.html"        },
  { match: "google docs",       href: "topics/case-google-docs.html"   },
  { match: "bitly",             href: "topics/case-bitly.html"         },
  { match: "url shorten",       href: "topics/case-bitly.html"         },
  { match: "dropbox",           href: "topics/case-dropbox.html"       },
  { match: "tinder",            href: "topics/case-tinder.html"        },
  { match: "zoom",              href: "topics/case-zoom.html"          },
  { match: "apple pay",         href: "topics/case-apple-pay.html"     },
  { match: "whatsapp supports 50b", href: "topics/case-whatsapp-engineering.html" },

  // FUNDAMENTALS — final wrap-up
  { match: "actor model",       href: "topics/fundamental-actor-model.html" },
  { match: "concurrency is not parallelism", href: "topics/fundamental-concurrency-vs-parallelism.html" },
  { match: "hinted handoff",    href: "topics/fundamental-hinted-handoff.html" },
  { match: "micro frontend",    href: "topics/fundamental-micro-frontends.html" },
  { match: "redis use case",    href: "topics/fundamental-redis-use-cases.html" },
  { match: "http header",       href: "topics/fundamental-http-headers.html" },
  { match: "passwords securely", href: "topics/fundamental-password-storage.html" },
  { match: "store passwords",   href: "topics/fundamental-password-storage.html" },
  { match: "frugal architecture", href: "topics/fundamental-frugal-architecture.html" },
  { match: "code review",       href: "topics/fundamental-code-review.html" },
  { match: "scale code reviews", href: "topics/fundamental-code-review.html" },
  { match: "pitfalls that break", href: "topics/fundamental-cloud-pitfalls.html" },
  { match: "cloud system",      href: "topics/fundamental-cloud-pitfalls.html" },
  { match: "troubleshoot",      href: "topics/fundamental-troubleshooting.html" },
  { match: "cannot access a website", href: "topics/fundamental-troubleshooting.html" },
  { match: "stacked diffs",     href: "topics/fundamental-stacked-diffs.html" },

  // FINAL FILL-IN
  { match: "ways to fail",      href: "topics/interview-failure-modes.html" },
  { match: "design-system-newsletter", href: "topics/interview-failure-modes.html" },
  { match: "interview cheat sheet", href: "topics/interview-cheat-sheet.html" },
  { match: "interview cheatsheet",  href: "topics/interview-cheat-sheet.html" },
  { match: "cybersecurity",     href: "topics/fundamental-cybersecurity-terms.html" },
  { match: "timsort",           href: "topics/fundamental-timsort.html" },
  { match: "mobile system design concepts", href: "topics/fundamental-mobile-architecture.html" },
  { match: "scale microservices", href: "topics/fundamental-scale-microservices.html" },
  { match: "scale microservices architecture", href: "topics/fundamental-scale-microservices.html" },
];

const CATS = [
  { id: "all",   name: "All" },
  { id: "case",  name: "Case Studies" },
  { id: "fund",  name: "Fundamentals" },
  { id: "int",   name: "Interview" },
  { id: "ai",    name: "AI Engineering" },
  { id: "paper", name: "White Papers" },
];
const CAT_LABEL = { case:"Case Study", fund:"Fundamental", int:"Interview", ai:"AI", paper:"White Paper" };
